//
//  accent.c
//
//  Created by Jeremy on 4/15/15.
//  Copyright (c) 2015 Jeremy March. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//


//#include <stdlib.h> // For random(), RAND_MAX
//#include <string.h>  //for strlen()
#ifndef __EMSCRIPTEN__
#include <stdio.h>
#include <string.h>
#include <assert.h>

#endif

#ifdef __ANDROID__
#include <android/log.h>
#endif

#include "GreekUnicode.h"
#include "accent.h"

#define  LOG_TAG    "your-log-tag"
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
// If you want you can add other log definition for info, warning etc

#define ALLOW_PRIVATE_USE_AREA 1
#define ALLOW_RHO_WITH_PSILI 0
#define MAX_COMBINING 6 //macron, breathing, accent, iota subscript || diaeresis, macron, accent, underdot

#ifdef __EMSCRIPTEN__
size_t strlen(const char *str)
{
    const char *s;
    for (s = str; *s; ++s) {}
    return(s - str);
}
#endif

char unicode_mode = PRECOMPOSED_MODE; //set default
bool addSpacingDiacriticIfNotLegal = false;

void allowSpacingDiacritics(bool val)
{
    addSpacingDiacriticIfNotLegal = val;
}

#define NUM_COMBINING_ACCENTS 10
//this is the order they will follow after the vowel
UCS2 combiningAccents[NUM_COMBINING_ACCENTS] = { COMBINING_MACRON, COMBINING_BREVE, COMBINING_DIAERESIS, COMBINING_ROUGH_BREATHING, COMBINING_SMOOTH_BREATHING, COMBINING_ACUTE, COMBINING_GRAVE, COMBINING_CIRCUMFLEX, COMBINING_IOTA_SUBSCRIPT, COMBINING_UNDERDOT };

//precomposed indices
enum {
    NORMAL,
    TONOS,
    DIALYTIKA_AND_TONOS,
    PSILI,                                  //smooth
    DASIA,                                  //rough
    OXIA,
    PSILI_AND_OXIA,
    DASIA_AND_OXIA,
    VARIA,
    PSILI_AND_VARIA,
    DASIA_AND_VARIA,
    PERISPOMENI,
    PSILI_AND_PERISPOMENI,
    DASIA_AND_PERISPOMENI,
    YPOGEGRAMMENI,
    PSILI_AND_YPOGEGRAMMENI,
    DASIA_AND_YPOGEGRAMMENI,
    OXIA_AND_YPOGEGRAMMENI,
    PSILI_AND_OXIA_AND_YPOGEGRAMMENI,
    DASIA_AND_OXIA_AND_YPOGEGRAMMENI,
    VARIA_AND_YPOGEGRAMMENI,
    PSILI_AND_VARIA_AND_YPOGEGRAMMENI,
    DASIA_AND_VARIA_AND_YPOGEGRAMMENI,
    PERISPOMENI_AND_YPOGEGRAMMENI,
    PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI,
    DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI,
    DIALYTIKA,
    DIALYTIKA_AND_OXIA,
    DIALYTIKA_AND_VARIA,
    DIALYTIKA_AND_PERISPOMENON,
    MACRON_PRECOMPOSED,
    BREVE_PRECOMPOSED,
#ifdef ALLOW_PRIVATE_USE_AREA
    MACRON_AND_SMOOTH,
    MACRON_AND_SMOOTH_AND_ACUTE,
    MACRON_AND_SMOOTH_AND_GRAVE,
    MACRON_AND_ROUGH,
    MACRON_AND_ROUGH_AND_ACUTE,
    MACRON_AND_ROUGH_AND_GRAVE,
    MACRON_AND_ACUTE,
    MACRON_AND_GRAVE,
    BREVE_AND_SMOOTH,
    BREVE_AND_SMOOTH_AND_ACUTE,
    BREVE_AND_SMOOTH_AND_GRAVE,
    BREVE_AND_ROUGH,
    BREVE_AND_ROUGH_AND_ACUTE,
    BREVE_AND_ROUGH_AND_GRAVE,
    BREVE_AND_ACUTE,
    BREVE_AND_GRAVE,
#endif
    NUM_ACCENT_CODES
};

enum {
    NOSORT = 0,
    ALPHA_SORT,
    BETA_SORT,
    GAMMA_SORT,
    DELTA_SORT,
    EPSILON_SORT,
    ZETA_SORT,
    ETA_SORT,
    THETA_SORT,
    IOTA_SORT,
    KAPPA_SORT,
    LAMBDA_SORT,
    MU_SORT,
    NU_SORT,
    XI_SORT,
    OMICRON_SORT,
    PI_SORT,
    RHO_SORT,
    SIGMA_SORT,
    TAU_SORT,
    UPSILON_SORT,
    PHI_SORT,
    CHI_SORT,
    PSI_SORT,
    OMEGA_SORT
};

//letterIndices
enum {
    ALPHA,
    EPSILON,
    ETA,
    IOTA,
    OMICRON,
    UPSILON,
    OMEGA,
    ALPHA_CAP,
    EPSILON_CAP,
    ETA_CAP,
    IOTA_CAP,
    OMICRON_CAP,
    UPSILON_CAP,
    OMEGA_CAP,
    NUM_VOWEL_CODES
};

UCS2 letters[NUM_VOWEL_CODES][NUM_ACCENT_CODES] = {
    { GREEK_SMALL_LETTER_ALPHA, GREEK_SMALL_LETTER_ALPHA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA, GREEK_SMALL_LETTER_ALPHA_WITH_OXIA, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_ALPHA_WITH_VARIA, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_ALPHA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI, GREEK_SMALL_LETTER_ALPHA_WITH_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI, 0, 0, 0, 0,
        GREEK_SMALL_LETTER_ALPHA_WITH_MACRON, GREEK_SMALL_LETTER_ALPHA_WITH_VRACHY
#ifdef ALLOW_PRIVATE_USE_AREA
        , PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_MACRON2,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_VARIA_AND_BREVE
#endif
    },
    
    { GREEK_SMALL_LETTER_EPSILON,GREEK_SMALL_LETTER_EPSILON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_EPSILON_WITH_PSILI, GREEK_SMALL_LETTER_EPSILON_WITH_DASIA, GREEK_SMALL_LETTER_EPSILON_WITH_OXIA, GREEK_SMALL_LETTER_EPSILON_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_EPSILON_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_EPSILON_WITH_VARIA, GREEK_SMALL_LETTER_EPSILON_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_EPSILON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_SMALL_LETTER_ETA, GREEK_SMALL_LETTER_ETA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_ETA_WITH_PSILI, GREEK_SMALL_LETTER_ETA_WITH_DASIA, GREEK_SMALL_LETTER_ETA_WITH_OXIA, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_ETA_WITH_VARIA, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_ETA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI, GREEK_SMALL_LETTER_ETA_WITH_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_SMALL_LETTER_IOTA, GREEK_SMALL_LETTER_IOTA_WITH_TONOS, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_TONOS, GREEK_SMALL_LETTER_IOTA_WITH_PSILI, GREEK_SMALL_LETTER_IOTA_WITH_DASIA, GREEK_SMALL_LETTER_IOTA_WITH_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_PERISPOMENI,
        GREEK_SMALL_LETTER_IOTA_WITH_MACRON, GREEK_SMALL_LETTER_IOTA_WITH_VRACHY
#ifdef ALLOW_PRIVATE_USE_AREA
        , PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_VARIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_VARIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_VARIA_AND_BREVE
#endif
    },
    
    { GREEK_SMALL_LETTER_OMICRON, GREEK_SMALL_LETTER_OMICRON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_OMICRON_WITH_PSILI, GREEK_SMALL_LETTER_OMICRON_WITH_DASIA, GREEK_SMALL_LETTER_OMICRON_WITH_OXIA, GREEK_SMALL_LETTER_OMICRON_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_OMICRON_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_OMICRON_WITH_VARIA, GREEK_SMALL_LETTER_OMICRON_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_OMICRON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_SMALL_LETTER_UPSILON, GREEK_SMALL_LETTER_UPSILON_WITH_TONOS, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_TONOS, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA, GREEK_SMALL_LETTER_UPSILON_WITH_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_PERISPOMENI, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_PERISPOMENI,
        GREEK_SMALL_LETTER_UPSILON_WITH_MACRON, GREEK_SMALL_LETTER_UPSILON_WITH_VRACHY
#ifdef ALLOW_PRIVATE_USE_AREA
        , PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_VARIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_VARIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_OXIA_AND_BREVE,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_VARIA_AND_BREVE
#endif
    },
    
    { GREEK_SMALL_LETTER_OMEGA, GREEK_SMALL_LETTER_OMEGA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA, GREEK_SMALL_LETTER_OMEGA_WITH_OXIA, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_OMEGA_WITH_VARIA, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_OMEGA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI, GREEK_SMALL_LETTER_OMEGA_WITH_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    /* START CAPITALS */
    { GREEK_CAPITAL_LETTER_ALPHA,GREEK_CAPITAL_LETTER_ALPHA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_OXIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_VARIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_OXIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_VARIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_PERISPOMENI_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI, 0, 0, 0, 0, GREEK_CAPITAL_LETTER_ALPHA_WITH_MACRON, GREEK_CAPITAL_LETTER_ALPHA_WITH_VRACHY
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_EPSILON, GREEK_CAPITAL_LETTER_EPSILON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_EPSILON_WITH_PSILI, GREEK_CAPITAL_LETTER_EPSILON_WITH_DASIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_OXIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_VARIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_ETA, GREEK_CAPITAL_LETTER_ETA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA, GREEK_CAPITAL_LETTER_ETA_WITH_OXIA, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_ETA_WITH_VARIA, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ETA_WITH_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_OXIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_VARIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_PERISPOMENI_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_IOTA, GREEK_CAPITAL_LETTER_IOTA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA, GREEK_CAPITAL_LETTER_IOTA_WITH_OXIA, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_IOTA_WITH_VARIA, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_IOTA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GREEK_CAPITAL_LETTER_IOTA_WITH_DIALYTIKA, 0, 0, 0, GREEK_CAPITAL_LETTER_IOTA_WITH_MACRON, GREEK_CAPITAL_LETTER_IOTA_WITH_VRACHY
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    { GREEK_CAPITAL_LETTER_OMICRON, GREEK_CAPITAL_LETTER_OMICRON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_OMICRON_WITH_PSILI, GREEK_CAPITAL_LETTER_OMICRON_WITH_DASIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_OXIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_VARIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_UPSILON, GREEK_CAPITAL_LETTER_UPSILON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA, GREEK_CAPITAL_LETTER_UPSILON_WITH_OXIA, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI_AND_OXIA*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_UPSILON_WITH_VARIA, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI_AND_VARIA*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PERISPOMENI*/, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI_AND_PERISPOMENI*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GREEK_CAPITAL_LETTER_UPSILON_WITH_DIALYTIKA, 0, 0, 0, GREEK_CAPITAL_LETTER_UPSILON_WITH_MACRON, GREEK_CAPITAL_LETTER_UPSILON_WITH_VRACHY
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_OMEGA, GREEK_CAPITAL_LETTER_OMEGA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_OXIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_VARIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_OXIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_VARIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_PERISPOMENI_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#endif
    }
};

#define NOCHAR 0

#define NOT_ACCENTABLE_CHAR 1
#define ACCENTABLE_CHAR 3



//first col will be the actual codepoint for an accenting character
//or NOT_ACCENTABLE_CHAR or NOCHAR
const UCS2 basicGreekLookUp[][3] = {
    /* 0370 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0371 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0372 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0373 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0374 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0375 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0376 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0377 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0378 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0379 */ { NOCHAR, NOCHAR, NOSORT },
    /* 037A */ { NOCHAR, NOCHAR, NOSORT },
    /* 037B */ { NOCHAR, NOCHAR, NOSORT },
    /* 037C */ { NOCHAR, NOCHAR, NOSORT },
    /* 037D */ { NOCHAR, NOCHAR, NOSORT },
    /* 037E */ { NOCHAR, NOCHAR, NOSORT },
    /* 037F */ { NOCHAR, NOCHAR, NOSORT },
    /* 0380 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0381 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0382 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0383 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0384 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0385 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0386 */ { GREEK_CAPITAL_LETTER_ALPHA, _ACUTE, ALPHA_SORT },
    /* 0387 */ { NOCHAR, NOCHAR, NOSORT },
    /* 0388 */ { GREEK_CAPITAL_LETTER_EPSILON, _ACUTE, EPSILON_SORT },
    /* 0389 */ { GREEK_CAPITAL_LETTER_ETA, _ACUTE, ETA_SORT },
    /* 038A */ { GREEK_CAPITAL_LETTER_IOTA, _ACUTE, IOTA_SORT },
    /* 038B */ { NOCHAR, NOCHAR, NOSORT },
    /* 038C */ { GREEK_CAPITAL_LETTER_OMICRON, _ACUTE, OMICRON_SORT },
    /* 038D */ { NOCHAR, NOCHAR, NOSORT },
    /* 038E */ { GREEK_CAPITAL_LETTER_UPSILON, _ACUTE, UPSILON_SORT },
    /* 038F */ { GREEK_CAPITAL_LETTER_OMEGA, _ACUTE, OMEGA_SORT },
    /* 0390 */ { GREEK_SMALL_LETTER_IOTA, _ACUTE | _DIAERESIS, IOTA_SORT },
    /* 0391 */ { GREEK_CAPITAL_LETTER_ALPHA, 0, ALPHA_SORT },
    /* 0392 */ { NOT_ACCENTABLE_CHAR, NOCHAR, BETA_SORT }, /* capital beta */
    /* 0393 */ { NOT_ACCENTABLE_CHAR, NOCHAR, GAMMA_SORT }, /* capital gamma */
    /* 0394 */ { NOT_ACCENTABLE_CHAR, NOCHAR, DELTA_SORT }, /* capital delta */
    /* 0395 */ { GREEK_CAPITAL_LETTER_EPSILON, 0 , EPSILON_SORT},
    /* 0396 */ { NOT_ACCENTABLE_CHAR, NOCHAR, ZETA_SORT }, /* capital zeta */
    /* 0397 */ { GREEK_CAPITAL_LETTER_ETA, 0, ETA_SORT },
    /* 0398 */ { NOT_ACCENTABLE_CHAR, NOCHAR, THETA_SORT }, /* capital theta */
    /* 0399 */ { GREEK_CAPITAL_LETTER_IOTA, 0, IOTA_SORT },
    /* 039A */ { NOT_ACCENTABLE_CHAR, NOCHAR, KAPPA_SORT }, /* capital kappa */
    /* 039B */ { NOT_ACCENTABLE_CHAR, NOCHAR, LAMBDA_SORT }, /* capital lambda */
    /* 039C */ { NOT_ACCENTABLE_CHAR, NOCHAR, MU_SORT }, /* capital mu */
    /* 039D */ { NOT_ACCENTABLE_CHAR, NOCHAR, NU_SORT }, /* capital nu */
    /* 039E */ { NOT_ACCENTABLE_CHAR, NOCHAR, XI_SORT }, /* capital xi */
    /* 039F */ { GREEK_CAPITAL_LETTER_OMICRON, 0, OMICRON_SORT },
    /* 03A0 */ { NOT_ACCENTABLE_CHAR, NOCHAR, PI_SORT }, /* capital pi */
    /* 03A1 */ { NOT_ACCENTABLE_CHAR, NOCHAR, RHO_SORT }, /* capital rho */
    /* 03A2 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03A3 */ { NOT_ACCENTABLE_CHAR, NOCHAR, SIGMA_SORT }, /* capital sigma */
    /* 03A4 */ { NOT_ACCENTABLE_CHAR, NOCHAR, TAU_SORT }, /* capital tau */
    /* 03A5 */ { GREEK_CAPITAL_LETTER_UPSILON, 0, UPSILON_SORT },
    /* 03A6 */ { NOT_ACCENTABLE_CHAR, NOCHAR, PHI_SORT }, /* capital phi */
    /* 03A7 */ { NOT_ACCENTABLE_CHAR, NOCHAR, CHI_SORT }, /* capital chi */
    /* 03A8 */ { NOT_ACCENTABLE_CHAR, NOCHAR, PSI_SORT }, /* capital psi */
    /* 03A9 */ { GREEK_CAPITAL_LETTER_OMEGA, 0, OMEGA_SORT },
    /* 03AA */ { GREEK_CAPITAL_LETTER_IOTA, _DIAERESIS, IOTA_SORT },
    /* 03AB */ { GREEK_CAPITAL_LETTER_UPSILON, _DIAERESIS, UPSILON_SORT },
    /* 03AC */ { GREEK_SMALL_LETTER_ALPHA, _ACUTE, ALPHA_SORT },
    /* 03AD */ { GREEK_SMALL_LETTER_EPSILON, _ACUTE, EPSILON_SORT },
    /* 03AE */ { GREEK_SMALL_LETTER_ETA, _ACUTE, ETA_SORT },
    /* 03AF */ { GREEK_SMALL_LETTER_IOTA, _ACUTE, IOTA_SORT },
    /* 03B0 */ { GREEK_SMALL_LETTER_UPSILON, _ACUTE | _DIAERESIS },
    /* 03B1 */ { GREEK_SMALL_LETTER_ALPHA, 0, ALPHA_SORT },
    /* 03B2 */ { NOT_ACCENTABLE_CHAR, NOCHAR, BETA_SORT }, /* small beta */
    /* 03B3 */ { NOT_ACCENTABLE_CHAR, NOCHAR, GAMMA_SORT }, /* small gamma */
    /* 03B4 */ { NOT_ACCENTABLE_CHAR, NOCHAR, DELTA_SORT }, /* small delta */
    /* 03B5 */ { GREEK_SMALL_LETTER_EPSILON, 0, EPSILON_SORT },
    /* 03B6 */ { NOT_ACCENTABLE_CHAR, NOCHAR, ZETA_SORT }, /* small zeta */
    /* 03B7 */ { GREEK_SMALL_LETTER_ETA, 0, ETA_SORT },
    /* 03B8 */ { NOT_ACCENTABLE_CHAR, NOCHAR, THETA_SORT }, /* small theta */
    /* 03B9 */ { GREEK_SMALL_LETTER_IOTA, 0, IOTA_SORT },
    /* 03BA */ { NOT_ACCENTABLE_CHAR, NOCHAR, KAPPA_SORT }, /* small kappa */
    /* 03BB */ { NOT_ACCENTABLE_CHAR, NOCHAR, LAMBDA_SORT }, /* small lambda */
    /* 03BC */ { NOT_ACCENTABLE_CHAR, NOCHAR, MU_SORT }, /* small mu */
    /* 03BD */ { NOT_ACCENTABLE_CHAR, NOCHAR, NU_SORT }, /* small nu */
    /* 03BE */ { NOT_ACCENTABLE_CHAR, NOCHAR, XI_SORT }, /* small xi */
    /* 03BF */ { GREEK_SMALL_LETTER_OMICRON, 0, OMICRON_SORT },
    /* 03C0 */ { NOT_ACCENTABLE_CHAR, NOCHAR, PI_SORT }, /* small pi */
    /* 03C1 */ { NOT_ACCENTABLE_CHAR, NOCHAR, RHO_SORT }, /* small rho */
    /* 03C2 */ { NOT_ACCENTABLE_CHAR, NOCHAR, SIGMA_SORT }, /* small final sigma */
    /* 03C3 */ { NOT_ACCENTABLE_CHAR, NOCHAR, SIGMA_SORT }, /* small sigma */
    /* 03C4 */ { NOT_ACCENTABLE_CHAR, NOCHAR, TAU_SORT }, /* small tau */
    /* 03C5 */ { GREEK_SMALL_LETTER_UPSILON, 0, UPSILON_SORT },
    /* 03C6 */ { NOT_ACCENTABLE_CHAR, NOCHAR, PHI_SORT }, /* small phi */
    /* 03C7 */ { NOT_ACCENTABLE_CHAR, NOCHAR, CHI_SORT }, /* small chi */
    /* 03C8 */ { NOT_ACCENTABLE_CHAR, NOCHAR, PSI_SORT }, /* small psi */
    /* 03C9 */ { GREEK_SMALL_LETTER_OMEGA, 0, OMEGA_SORT },
    /* 03CA */ { GREEK_SMALL_LETTER_IOTA, _DIAERESIS, IOTA_SORT },
    /* 03CB */ { GREEK_SMALL_LETTER_UPSILON, _DIAERESIS, UPSILON_SORT },
    /* 03CC */ { GREEK_SMALL_LETTER_OMICRON, _ACUTE, OMICRON_SORT },
    /* 03CD */ { GREEK_SMALL_LETTER_UPSILON, _ACUTE, UPSILON_SORT },
    /* 03CE */ { GREEK_SMALL_LETTER_OMEGA, _ACUTE, OMEGA_SORT },
    /* 03CF */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D0 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D1 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D2 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D3 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D4 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D5 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D6 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D7 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D8 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03D9 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03DA */ { NOCHAR, NOCHAR, NOSORT },
    /* 03DB */ { NOCHAR, NOCHAR, NOSORT },
    /* 03DC */ { NOCHAR, NOCHAR, NOSORT },
    /* 03DD */ { NOCHAR, NOCHAR, NOSORT },
    /* 03DE */ { NOCHAR, NOCHAR, NOSORT },
    /* 03DF */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E0 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E1 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E2 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E3 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E4 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E5 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E6 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E7 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E8 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03E9 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03EA */ { NOCHAR, NOCHAR, NOSORT },
    /* 03EB */ { NOCHAR, NOCHAR, NOSORT },
    /* 03EC */ { NOCHAR, NOCHAR, NOSORT },
    /* 03ED */ { NOCHAR, NOCHAR, NOSORT },
    /* 03EE */ { NOCHAR, NOCHAR, NOSORT },
    /* 03EF */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F0 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F1 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F2 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F3 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F4 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F5 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F6 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F7 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F8 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03F9 */ { NOCHAR, NOCHAR, NOSORT },
    /* 03FA */ { NOCHAR, NOCHAR, NOSORT },
    /* 03FB */ { NOCHAR, NOCHAR, NOSORT },
    /* 03FC */ { NOCHAR, NOCHAR, NOSORT },
    /* 03FD */ { NOCHAR, NOCHAR, NOSORT },
    /* 03FE */ { NOCHAR, NOCHAR, NOSORT },
    /* 03FF */ { NOCHAR, NOCHAR, NOSORT }
};

const UCS2 extendedGreekLookUp[][2] = {
    /* 1F00 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH },
    /* 1F01 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH },
    /* 1F02 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _GRAVE },
    /* 1F03 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _GRAVE },
    /* 1F04 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _ACUTE },
    /* 1F05 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _ACUTE },
    /* 1F06 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _CIRCUMFLEX },
    /* 1F07 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _CIRCUMFLEX },
    /* 1F08 */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH },
    /* 1F09 */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH },
    /* 1F0A */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _GRAVE },
    /* 1F0B */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _GRAVE },
    /* 1F0C */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _ACUTE },
    /* 1F0D */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _ACUTE },
    /* 1F0E */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _CIRCUMFLEX },
    /* 1F0F */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _CIRCUMFLEX },
    /* 1F10 */ { GREEK_SMALL_LETTER_EPSILON, _SMOOTH },
    /* 1F11 */ { GREEK_SMALL_LETTER_EPSILON, _ROUGH },
    /* 1F12 */ { GREEK_SMALL_LETTER_EPSILON, _SMOOTH | _GRAVE },
    /* 1F13 */ { GREEK_SMALL_LETTER_EPSILON, _ROUGH | _GRAVE },
    /* 1F14 */ { GREEK_SMALL_LETTER_EPSILON, _SMOOTH | _ACUTE },
    /* 1F15 */ { GREEK_SMALL_LETTER_EPSILON, _ROUGH | _ACUTE },
    /* 1F16 */ { NOCHAR, NOCHAR },
    /* 1F17 */ { NOCHAR, NOCHAR },
    /* 1F18 */ { GREEK_CAPITAL_LETTER_EPSILON, _SMOOTH },
    /* 1F19 */ { GREEK_CAPITAL_LETTER_EPSILON, _ROUGH },
    /* 1F1A */ { GREEK_CAPITAL_LETTER_EPSILON, _SMOOTH | _GRAVE },
    /* 1F1B */ { GREEK_CAPITAL_LETTER_EPSILON, _ROUGH | _GRAVE },
    /* 1F1C */ { GREEK_CAPITAL_LETTER_EPSILON, _SMOOTH | _ACUTE },
    /* 1F1D */ { GREEK_CAPITAL_LETTER_EPSILON, _ROUGH | _ACUTE },
    /* 1F1E */ { NOCHAR, NOCHAR },
    /* 1F1F */ { NOCHAR, NOCHAR },
    /* 1F20 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH },
    /* 1F21 */ { GREEK_SMALL_LETTER_ETA, _ROUGH },
    /* 1F22 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _GRAVE },
    /* 1F23 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _GRAVE },
    /* 1F24 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _ACUTE },
    /* 1F25 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _ACUTE },
    /* 1F26 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _CIRCUMFLEX },
    /* 1F27 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _CIRCUMFLEX },
    /* 1F28 */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH },
    /* 1F29 */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH },
    /* 1F2A */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _GRAVE },
    /* 1F2B */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _GRAVE },
    /* 1F2C */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _ACUTE },
    /* 1F2D */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _ACUTE },
    /* 1F2E */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _CIRCUMFLEX },
    /* 1F2F */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _CIRCUMFLEX },
    /* 1F30 */ { GREEK_SMALL_LETTER_IOTA, _SMOOTH },
    /* 1F31 */ { GREEK_SMALL_LETTER_IOTA, _ROUGH },
    /* 1F32 */ { GREEK_SMALL_LETTER_IOTA, _SMOOTH | _GRAVE },
    /* 1F33 */ { GREEK_SMALL_LETTER_IOTA, _ROUGH | _GRAVE },
    /* 1F34 */ { GREEK_SMALL_LETTER_IOTA, _SMOOTH | _ACUTE },
    /* 1F35 */ { GREEK_SMALL_LETTER_IOTA, _ROUGH | _ACUTE },
    /* 1F36 */ { GREEK_SMALL_LETTER_IOTA, _SMOOTH | _CIRCUMFLEX },
    /* 1F37 */ { GREEK_SMALL_LETTER_IOTA, _ROUGH | _CIRCUMFLEX },
    /* 1F38 */ { GREEK_CAPITAL_LETTER_IOTA, _SMOOTH },
    /* 1F39 */ { GREEK_CAPITAL_LETTER_IOTA, _ROUGH },
    /* 1F3A */ { GREEK_CAPITAL_LETTER_IOTA, _SMOOTH | _GRAVE },
    /* 1F3B */ { GREEK_CAPITAL_LETTER_IOTA, _ROUGH | _GRAVE },
    /* 1F3C */ { GREEK_CAPITAL_LETTER_IOTA, _SMOOTH | _ACUTE },
    /* 1F3D */ { GREEK_CAPITAL_LETTER_IOTA, _ROUGH | _ACUTE },
    /* 1F3E */ { GREEK_CAPITAL_LETTER_IOTA, _SMOOTH | _CIRCUMFLEX },
    /* 1F3F */ { GREEK_CAPITAL_LETTER_IOTA, _ROUGH | _CIRCUMFLEX },
    /* 1F40 */ { GREEK_SMALL_LETTER_OMICRON, _SMOOTH },
    /* 1F41 */ { GREEK_SMALL_LETTER_OMICRON, _ROUGH },
    /* 1F42 */ { GREEK_SMALL_LETTER_OMICRON, _SMOOTH | _GRAVE },
    /* 1F43 */ { GREEK_SMALL_LETTER_OMICRON, _ROUGH | _GRAVE },
    /* 1F44 */ { GREEK_SMALL_LETTER_OMICRON, _SMOOTH | _ACUTE },
    /* 1F45 */ { GREEK_SMALL_LETTER_OMICRON, _ROUGH | _ACUTE },
    /* 1F46 */ { NOCHAR, NOCHAR },
    /* 1F47 */ { NOCHAR, NOCHAR },
    /* 1F48 */ { GREEK_CAPITAL_LETTER_OMICRON, _SMOOTH },
    /* 1F49 */ { GREEK_CAPITAL_LETTER_OMICRON, _ROUGH },
    /* 1F4A */ { GREEK_CAPITAL_LETTER_OMICRON, _SMOOTH | _GRAVE },
    /* 1F4B */ { GREEK_CAPITAL_LETTER_OMICRON, _ROUGH | _GRAVE },
    /* 1F4C */ { GREEK_CAPITAL_LETTER_OMICRON, _SMOOTH | _ACUTE },
    /* 1F4D */ { GREEK_CAPITAL_LETTER_OMICRON, _ROUGH | _ACUTE },
    /* 1F4E */ { NOCHAR, NOCHAR },
    /* 1F4F */ { NOCHAR, NOCHAR },
    /* 1F50 */ { GREEK_SMALL_LETTER_UPSILON, _SMOOTH },
    /* 1F51 */ { GREEK_SMALL_LETTER_UPSILON, _ROUGH },
    /* 1F52 */ { GREEK_SMALL_LETTER_UPSILON, _SMOOTH | _GRAVE },
    /* 1F53 */ { GREEK_SMALL_LETTER_UPSILON, _ROUGH | _GRAVE },
    /* 1F54 */ { GREEK_SMALL_LETTER_UPSILON, _SMOOTH | _ACUTE },
    /* 1F55 */ { GREEK_SMALL_LETTER_UPSILON, _ROUGH | _ACUTE },
    /* 1F56 */ { GREEK_SMALL_LETTER_UPSILON, _SMOOTH | _CIRCUMFLEX },
    /* 1F57 */ { GREEK_SMALL_LETTER_UPSILON, _ROUGH | _CIRCUMFLEX },
    /* 1F58 */ { NOCHAR, NOCHAR },
    /* 1F59 */ { GREEK_CAPITAL_LETTER_UPSILON, _ROUGH },
    /* 1F5A */ { NOCHAR, NOCHAR },
    /* 1F5B */ { GREEK_CAPITAL_LETTER_UPSILON, _ROUGH | _GRAVE },
    /* 1F5C */ { NOCHAR, NOCHAR },
    /* 1F5D */ { GREEK_CAPITAL_LETTER_UPSILON, _ROUGH | _ACUTE },
    /* 1F5E */ { NOCHAR, NOCHAR },
    /* 1F5F */ { GREEK_CAPITAL_LETTER_UPSILON, _ROUGH | _CIRCUMFLEX },
    /* 1F60 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH },
    /* 1F61 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH },
    /* 1F62 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _GRAVE },
    /* 1F63 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _GRAVE },
    /* 1F64 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _ACUTE },
    /* 1F65 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _ACUTE },
    /* 1F66 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _CIRCUMFLEX },
    /* 1F67 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _CIRCUMFLEX },
    /* 1F68 */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH },
    /* 1F69 */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH },
    /* 1F6A */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _GRAVE },
    /* 1F6B */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _GRAVE },
    /* 1F6C */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _ACUTE },
    /* 1F6D */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _ACUTE },
    /* 1F6E */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _CIRCUMFLEX },
    /* 1F6F */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _CIRCUMFLEX },
    /* 1F70 */ { GREEK_SMALL_LETTER_ALPHA, _GRAVE },
    /* 1F71 */ { GREEK_SMALL_LETTER_ALPHA, _ACUTE },
    /* 1F72 */ { GREEK_SMALL_LETTER_EPSILON, _GRAVE },
    /* 1F73 */ { GREEK_SMALL_LETTER_EPSILON, _ACUTE },
    /* 1F74 */ { GREEK_SMALL_LETTER_ETA, _GRAVE },
    /* 1F75 */ { GREEK_SMALL_LETTER_ETA, _ACUTE },
    /* 1F76 */ { GREEK_SMALL_LETTER_IOTA, _GRAVE },
    /* 1F77 */ { GREEK_SMALL_LETTER_IOTA, _ACUTE },
    /* 1F78 */ { GREEK_SMALL_LETTER_OMICRON, _GRAVE },
    /* 1F79 */ { GREEK_SMALL_LETTER_OMICRON, _ACUTE },
    /* 1F7A */ { GREEK_SMALL_LETTER_UPSILON, _GRAVE },
    /* 1F7B */ { GREEK_SMALL_LETTER_UPSILON, _ACUTE },
    /* 1F7C */ { GREEK_SMALL_LETTER_OMEGA, _GRAVE },
    /* 1F7D */ { GREEK_SMALL_LETTER_OMEGA, _ACUTE },
    /* 1F7E */ { NOCHAR, NOCHAR },
    /* 1F7F */ { NOCHAR, NOCHAR },
    /* 1F80 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _IOTA_SUB },
    /* 1F81 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _IOTA_SUB },
    /* 1F82 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _GRAVE | _IOTA_SUB },
    /* 1F83 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _GRAVE | _IOTA_SUB },
    /* 1F84 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _ACUTE | _IOTA_SUB },
    /* 1F85 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _ACUTE | _IOTA_SUB },
    /* 1F86 */ { GREEK_SMALL_LETTER_ALPHA, _SMOOTH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F87 */ { GREEK_SMALL_LETTER_ALPHA, _ROUGH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F88 */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _IOTA_SUB },
    /* 1F89 */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _IOTA_SUB },
    /* 1F8A */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _GRAVE | _IOTA_SUB },
    /* 1F8B */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _GRAVE | _IOTA_SUB },
    /* 1F8C */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _ACUTE | _IOTA_SUB },
    /* 1F8D */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _ACUTE | _IOTA_SUB },
    /* 1F8E */ { GREEK_CAPITAL_LETTER_ALPHA, _SMOOTH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F8F */ { GREEK_CAPITAL_LETTER_ALPHA, _ROUGH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F90 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _IOTA_SUB },
    /* 1F91 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _IOTA_SUB },
    /* 1F92 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _GRAVE | _IOTA_SUB },
    /* 1F93 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _GRAVE | _IOTA_SUB },
    /* 1F94 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _ACUTE | _IOTA_SUB },
    /* 1F95 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _ACUTE | _IOTA_SUB },
    /* 1F96 */ { GREEK_SMALL_LETTER_ETA, _SMOOTH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F97 */ { GREEK_SMALL_LETTER_ETA, _ROUGH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F98 */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _IOTA_SUB },
    /* 1F99 */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _IOTA_SUB },
    /* 1F9A */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _GRAVE | _IOTA_SUB },
    /* 1F9B */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _GRAVE | _IOTA_SUB },
    /* 1F9C */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _ACUTE | _IOTA_SUB },
    /* 1F9D */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _ACUTE | _IOTA_SUB },
    /* 1F9E */ { GREEK_CAPITAL_LETTER_ETA, _SMOOTH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1F9F */ { GREEK_CAPITAL_LETTER_ETA, _ROUGH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1FA0 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _IOTA_SUB },
    /* 1FA1 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _IOTA_SUB },
    /* 1FA2 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _GRAVE | _IOTA_SUB },
    /* 1FA3 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _GRAVE | _IOTA_SUB },
    /* 1FA4 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _ACUTE | _IOTA_SUB },
    /* 1FA5 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _ACUTE | _IOTA_SUB },
    /* 1FA6 */ { GREEK_SMALL_LETTER_OMEGA, _SMOOTH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1FA7 */ { GREEK_SMALL_LETTER_OMEGA, _ROUGH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1FA8 */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _IOTA_SUB },
    /* 1FA9 */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _IOTA_SUB },
    /* 1FAA */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _GRAVE | _IOTA_SUB },
    /* 1FAB */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _GRAVE | _IOTA_SUB },
    /* 1FAC */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _ACUTE | _IOTA_SUB },
    /* 1FAD */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _ACUTE | _IOTA_SUB },
    /* 1FAE */ { GREEK_CAPITAL_LETTER_OMEGA, _SMOOTH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1FAF */ { GREEK_CAPITAL_LETTER_OMEGA, _ROUGH | _CIRCUMFLEX | _IOTA_SUB },
    /* 1FB0 */ { GREEK_SMALL_LETTER_ALPHA, _BREVE }, //new
    /* 1FB1 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON },
    /* 1FB2 */ { GREEK_SMALL_LETTER_ALPHA, _GRAVE | _IOTA_SUB },
    /* 1FB3 */ { GREEK_SMALL_LETTER_ALPHA, _IOTA_SUB },
    /* 1FB4 */ { GREEK_SMALL_LETTER_ALPHA, _ACUTE | _IOTA_SUB },
    /* 1FB5 */ { NOCHAR, NOCHAR },
    /* 1FB6 */ { GREEK_SMALL_LETTER_ALPHA, _CIRCUMFLEX },
    /* 1FB7 */ { GREEK_SMALL_LETTER_ALPHA, _CIRCUMFLEX | _IOTA_SUB },
    /* 1FB8 */ { GREEK_CAPITAL_LETTER_ALPHA, _BREVE },
    /* 1FB9 */ {GREEK_CAPITAL_LETTER_ALPHA, _MACRON },
    /* 1FBA */ {GREEK_CAPITAL_LETTER_ALPHA, _GRAVE },
    /* 1FBB */ {GREEK_CAPITAL_LETTER_ALPHA, _ACUTE },
    /* 1FBC */ {GREEK_CAPITAL_LETTER_ALPHA, _IOTA_SUB },
    /* 1FBD */ { NOCHAR, NOCHAR },
    /* 1FBE */ { NOCHAR, NOCHAR },
    /* 1FBF */ { NOCHAR, NOCHAR },
    /* 1FC0 */ { NOCHAR, NOCHAR },
    /* 1FC1 */ { NOCHAR, NOCHAR },
    /* 1FC2 */ { GREEK_SMALL_LETTER_ETA, _GRAVE | _IOTA_SUB },
    /* 1FC3 */ { GREEK_SMALL_LETTER_ETA, _IOTA_SUB },
    /* 1FC4 */ { GREEK_SMALL_LETTER_ETA, _ACUTE | _IOTA_SUB },
    /* 1FC5 */ { NOCHAR, NOCHAR },
    /* 1FC6 */ { GREEK_SMALL_LETTER_ETA, _CIRCUMFLEX },
    /* 1FC7 */ { GREEK_SMALL_LETTER_ETA, _CIRCUMFLEX | _IOTA_SUB },
    /* 1FC8 */ { GREEK_CAPITAL_LETTER_EPSILON, _GRAVE },
    /* 1FC9 */ { GREEK_CAPITAL_LETTER_EPSILON, _ACUTE },
    /* 1FCA */ { GREEK_CAPITAL_LETTER_ETA, _GRAVE },
    /* 1FCB */ { GREEK_CAPITAL_LETTER_ETA, _ACUTE },
    /* 1FCC */ { GREEK_CAPITAL_LETTER_ETA, _IOTA_SUB },
    /* 1FCD */ { NOCHAR, NOCHAR },
    /* 1FCE */ { NOCHAR, NOCHAR },
    /* 1FCF */ { NOCHAR, NOCHAR },
    /* 1FD0 */ { GREEK_SMALL_LETTER_IOTA, _BREVE }, //new
    /* 1FD1 */ { GREEK_SMALL_LETTER_IOTA, _MACRON },
    /* 1FD2 */ { GREEK_SMALL_LETTER_IOTA, _DIAERESIS | _GRAVE },
    /* 1FD3 */ { GREEK_SMALL_LETTER_IOTA, _DIAERESIS | _ACUTE },
    /* 1FD4 */ { NOCHAR, NOCHAR },
    /* 1FD5 */ { NOCHAR, NOCHAR },
    /* 1FD6 */ { GREEK_SMALL_LETTER_IOTA, _CIRCUMFLEX },
    /* 1FD7 */ { GREEK_SMALL_LETTER_IOTA, _DIAERESIS | _CIRCUMFLEX },
    /* 1FD8 */ { GREEK_CAPITAL_LETTER_IOTA, _BREVE },
    /* 1FD9 */ { GREEK_CAPITAL_LETTER_IOTA, _MACRON },
    /* 1FDA */ { GREEK_CAPITAL_LETTER_IOTA, _GRAVE },
    /* 1FDB */ { GREEK_CAPITAL_LETTER_IOTA, _ACUTE },
    /* 1FDC */ { NOCHAR, NOCHAR },
    /* 1FDD */ { NOCHAR, NOCHAR },
    /* 1FDE */ { NOCHAR, NOCHAR },
    /* 1FDF */ { NOCHAR, NOCHAR },
    /* 1FE0 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE }, //new
    /* 1FE1 */ { GREEK_SMALL_LETTER_UPSILON, _MACRON },
    /* 1FE2 */ { GREEK_SMALL_LETTER_UPSILON, _DIAERESIS | _GRAVE },
    /* 1FE3 */ { GREEK_SMALL_LETTER_UPSILON, _DIAERESIS | _ACUTE },
    /* 1FE4 */ { GREEK_SMALL_LETTER_RHO, _SMOOTH },
    /* 1FE5 */ { GREEK_SMALL_LETTER_RHO, _ROUGH },
    /* 1FE6 */ { GREEK_SMALL_LETTER_UPSILON, _CIRCUMFLEX },
    /* 1FE7 */ { GREEK_SMALL_LETTER_UPSILON, _DIAERESIS | _CIRCUMFLEX },
    /* 1FE8 */ { GREEK_CAPITAL_LETTER_UPSILON, _BREVE },
    /* 1FE9 */ { GREEK_CAPITAL_LETTER_UPSILON, _MACRON },
    /* 1FEA */ { GREEK_CAPITAL_LETTER_UPSILON, _GRAVE },
    /* 1FEB */ { GREEK_CAPITAL_LETTER_UPSILON, _ACUTE },
    /* 1FEC */ { NOCHAR, NOCHAR },
    /* 1FED */ { NOCHAR, NOCHAR },
    /* 1FEE */ { NOCHAR, NOCHAR },
    /* 1FEF */ { NOCHAR, NOCHAR },
    /* 1FF0 */ { NOCHAR, NOCHAR },
    /* 1FF1 */ { NOCHAR, NOCHAR },
    /* 1FF2 */ { GREEK_SMALL_LETTER_OMEGA, _GRAVE | _IOTA_SUB },
    /* 1FF3 */ { GREEK_SMALL_LETTER_OMEGA, _IOTA_SUB },
    /* 1FF4 */ { GREEK_SMALL_LETTER_OMEGA, _ACUTE | _IOTA_SUB },
    /* 1FF5 */ { NOCHAR, NOCHAR },
    /* 1FF6 */ { GREEK_SMALL_LETTER_OMEGA, _CIRCUMFLEX },
    /* 1FF7 */ { GREEK_SMALL_LETTER_OMEGA, _CIRCUMFLEX | _IOTA_SUB },
    /* 1FF8 */ { GREEK_CAPITAL_LETTER_OMICRON, _GRAVE },
    /* 1FF9 */ { GREEK_CAPITAL_LETTER_OMICRON, _ACUTE },
    /* 1FFA */ { GREEK_CAPITAL_LETTER_OMEGA, _GRAVE },
    /* 1FFB */ { GREEK_CAPITAL_LETTER_OMEGA, _ACUTE },
    /* 1FFC */ { GREEK_CAPITAL_LETTER_OMEGA, _IOTA_SUB },
    /* 1FFD */ { NOCHAR, NOCHAR },
    /* 1FFE */ { NOCHAR, NOCHAR },
    /* 1FFF */ { NOCHAR, NOCHAR }
};

const UCS2 puaGreekLookUp[][2] = {
    /* EAF0 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _GRAVE },
    /* EAF1 */ { NOCHAR, NOCHAR },
    /* EAF2 */ { NOCHAR, NOCHAR },
    /* EAF3 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _SMOOTH | _GRAVE },
    /* EAF4 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _ROUGH | _GRAVE },
    /* EAF5 */ { NOCHAR, NOCHAR },
    /* EAF6 */ { NOCHAR, NOCHAR },
    /* EAF7 */ { NOCHAR, NOCHAR },
    /* EAF8 */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _GRAVE },
    /* EAF9 */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _SMOOTH },
    /* EAFA */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _SMOOTH | _GRAVE },
    /* EAFB */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _ROUGH | _ACUTE },
    /* EAFC */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _ROUGH | _GRAVE },
    /* EAFD */ { NOCHAR, NOCHAR },
    /* EAFE */ { NOCHAR, NOCHAR },
    /* EAFF */ { NOCHAR, NOCHAR },
    /* EB00 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _ACUTE },
    /* EB01 */ { NOCHAR, NOCHAR },
    /* EB02 */ { NOCHAR, NOCHAR },
    /* EB03 */ { NOCHAR, NOCHAR },
    /* EB04 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _SMOOTH },
    /* EB05 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _ROUGH },
    /* EB06 */ { NOCHAR, NOCHAR },
    /* EB07 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _SMOOTH | _ACUTE },
    /* EB08 */ { NOCHAR, NOCHAR },
    /* EB09 */ { GREEK_SMALL_LETTER_ALPHA, _MACRON | _ROUGH | _ACUTE },
    /* EB0A */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _ACUTE },
    /* EB0B */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _ROUGH },
    /* EB0C */ { GREEK_SMALL_LETTER_ALPHA, _BREVE | _SMOOTH | _ACUTE },
    /* EB0D */ { NOCHAR, NOCHAR },
    /* EB0E */ { NOCHAR, NOCHAR },
    /* EB0F */ { NOCHAR, NOCHAR },
    /* EB10 */ { NOCHAR, NOCHAR },
    /* EB11 */ { NOCHAR, NOCHAR },
    /* EB12 */ { NOCHAR, NOCHAR },
    /* EB13 */ { NOCHAR, NOCHAR },
    /* EB14 */ { NOCHAR, NOCHAR },
    /* EB15 */ { NOCHAR, NOCHAR },
    /* EB16 */ { NOCHAR, NOCHAR },
    /* EB17 */ { NOCHAR, NOCHAR },
    /* EB18 */ { NOCHAR, NOCHAR },
    /* EB19 */ { NOCHAR, NOCHAR },
    /* EB1A */ { NOCHAR, NOCHAR },
    /* EB1B */ { NOCHAR, NOCHAR },
    /* EB1C */ { NOCHAR, NOCHAR },
    /* EB1D */ { NOCHAR, NOCHAR },
    /* EB1E */ { NOCHAR, NOCHAR },
    /* EB1F */ { NOCHAR, NOCHAR },
    /* EB20 */ { NOCHAR, NOCHAR },
    /* EB21 */ { NOCHAR, NOCHAR },
    /* EB22 */ { NOCHAR, NOCHAR },
    /* EB23 */ { NOCHAR, NOCHAR },
    /* EB24 */ { NOCHAR, NOCHAR },
    /* EB25 */ { NOCHAR, NOCHAR },
    /* EB26 */ { NOCHAR, NOCHAR },
    /* EB27 */ { NOCHAR, NOCHAR },
    /* EB28 */ { NOCHAR, NOCHAR },
    /* EB29 */ { NOCHAR, NOCHAR },
    /* EB2A */ { NOCHAR, NOCHAR },
    /* EB2B */ { NOCHAR, NOCHAR },
    /* EB2C */ { NOCHAR, NOCHAR },
    /* EB2D */ { NOCHAR, NOCHAR },
    /* EB2E */ { NOCHAR, NOCHAR },
    /* EB2F */ { NOCHAR, NOCHAR },
    /* EB30 */ { NOCHAR, NOCHAR },
    /* EB31 */ { NOCHAR, NOCHAR },
    /* EB32 */ { NOCHAR, NOCHAR },
    /* EB33 */ { NOCHAR, NOCHAR },
    /* EB34 */ { NOCHAR, NOCHAR },
    /* EB35 */ { NOCHAR, NOCHAR },
    /* EB36 */ { NOCHAR, NOCHAR },
    /* EB37 */ { NOCHAR, NOCHAR },
    /* EB38 */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _GRAVE },
    /* EB39 */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _ACUTE },
    /* EB3A */ { NOCHAR, NOCHAR },
    /* EB3B */ { NOCHAR, NOCHAR },
    /* EB3C */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _SMOOTH },
    /* EB3D */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _SMOOTH | _ACUTE },
    /* EB3E */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _ROUGH },
    /* EB3F */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _ROUGH | _ACUTE },
    /* EB40 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _ACUTE },
    /* EB41 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _SMOOTH },
    /* EB42 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _SMOOTH | _ACUTE },
    /* EB43 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _ROUGH },
    /* EB44 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _GRAVE },
    /* EB45 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _SMOOTH | _GRAVE },
    /* EB46 */ { NOCHAR, NOCHAR },
    /* EB47 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _ROUGH | _ACUTE },
    /* EB48 */ { GREEK_SMALL_LETTER_IOTA, _BREVE | _ROUGH | _GRAVE },
    /* EB49 */ { NOCHAR, NOCHAR },
    /* EB4A */ { NOCHAR, NOCHAR },
    /* EB4B */ { NOCHAR, NOCHAR },
    /* EB4C */ { NOCHAR, NOCHAR },
    /* EB4D */ { NOCHAR, NOCHAR },
    /* EB4E */ { NOCHAR, NOCHAR },
    /* EB4F */ { NOCHAR, NOCHAR },
    /* EB50 */ { NOCHAR, NOCHAR },
    /* EB51 */ { NOCHAR, NOCHAR },
    /* EB52 */ { NOCHAR, NOCHAR },
    /* EB53 */ { NOCHAR, NOCHAR },
    /* EB54 */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _SMOOTH | _GRAVE },
    /* EB55 */ { GREEK_SMALL_LETTER_IOTA, _MACRON | _ROUGH | _GRAVE },
    /* EB56 */ { NOCHAR, NOCHAR },
    /* EB57 */ { NOCHAR, NOCHAR },
    /* EB58 */ { NOCHAR, NOCHAR },
    /* EB59 */ { NOCHAR, NOCHAR },
    /* EB5A */ { NOCHAR, NOCHAR },
    /* EB5B */ { NOCHAR, NOCHAR },
    /* EB5C */ { NOCHAR, NOCHAR },
    /* EB5D */ { NOCHAR, NOCHAR },
    /* EB5E */ { NOCHAR, NOCHAR },
    /* EB5F */ { NOCHAR, NOCHAR },
    /* EB60 */ { NOCHAR, NOCHAR },
    /* EB61 */ { NOCHAR, NOCHAR },
    /* EB62 */ { NOCHAR, NOCHAR },
    /* EB63 */ { NOCHAR, NOCHAR },
    /* EB64 */ { NOCHAR, NOCHAR },
    /* EB65 */ { NOCHAR, NOCHAR },
    /* EB66 */ { NOCHAR, NOCHAR },
    /* EB67 */ { NOCHAR, NOCHAR },
    /* EB68 */ { NOCHAR, NOCHAR },
    /* EB69 */ { NOCHAR, NOCHAR },
    /* EB6A */ { NOCHAR, NOCHAR },
    /* EB6B */ { NOCHAR, NOCHAR },
    /* EB6C */ { NOCHAR, NOCHAR },
    /* EB6D */ { NOCHAR, NOCHAR },
    /* EB6E */ { NOCHAR, NOCHAR },
    /* EB6F */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _GRAVE },
    /* EB70 */ { NOCHAR, NOCHAR },
    /* EB71 */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _SMOOTH | _GRAVE },
    /* EB72 */ { NOCHAR, NOCHAR },
    /* EB73 */ { NOCHAR, NOCHAR },
    /* EB74 */ { NOCHAR, NOCHAR },
    /* EB75 */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _ROUGH | _GRAVE },
    /* EB76 */ { NOCHAR, NOCHAR },
    /* EB77 */ { NOCHAR, NOCHAR },
    /* EB78 */ { NOCHAR, NOCHAR },
    /* EB79 */ { NOCHAR, NOCHAR },
    /* EB7A */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _ACUTE },
    /* EB7B */ { NOCHAR, NOCHAR },
    /* EB7C */ { NOCHAR, NOCHAR },
    /* EB7D */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _SMOOTH },
    /* EB7E */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _ROUGH },
    /* EB7F */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _SMOOTH | _ACUTE },
    /* EB80 */ { GREEK_SMALL_LETTER_UPSILON, _MACRON | _ROUGH | _ACUTE },

    /* EB81 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _ACUTE },
    /* EB82 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _ROUGH },
    /* EB83 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _GRAVE },
    /* EB84 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _SMOOTH },
    /* EB85 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _SMOOTH | _ACUTE },
    /* EB86 */ { NOCHAR, NOCHAR },
    /* EB87 */ { NOCHAR, NOCHAR },
    /* EB88 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _SMOOTH | _GRAVE },
    /* EB89 */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _ROUGH | _ACUTE },
    /* EB8A */ { GREEK_SMALL_LETTER_UPSILON, _BREVE | _ROUGH | _GRAVE }
};
/*
bool analyzePrecomposedLetterOLD(UCS2 letter, int *l, int *a)
{
    for (*l = 0; *l < NUM_VOWEL_CODES; (*l)++)
    {
        for (*a = 0; *a < NUM_ACCENT_CODES; (*a)++)
        {
            if (letter == letters[*l][*a])
            {
                //fprintf(stderr, "letter: %d, accent: %d", *l, *a);
                return true;
            }
        }
    }
    return false;
}
*/

/*
 return NOCHAR if the character is invalid greek, NOT_ACCENTABLE_CHAR if it is a consonant,
 or ACCENTABLE_CHAR if it is a vowel.
 For ACCENTABLE_CHAR it puts the base vowel in *l and an accentBitMask in *a
 For NOT_ACCENTABLE_CHAR it puts the consonant in *l which will be the same as letterToAnalyze
 */
int analyzePrecomposedLetter(UCS2 letterToAnalyze, UCS2 *l, unsigned int *diacritics)
{
    //*diacritics: do not initialize it, its value is being added to here
    int offset = 0;
    UCS2 returnChar = 0; //will be NOCHAR, NOT_ACCENTABLE_CHAR, or the base vowel if ACCENTABLE_CHAR
    if (letterToAnalyze >= 0x0370 && letterToAnalyze <= 0x03FF)
    {
        offset = letterToAnalyze - 0x0370;
        //*l = basicGreekLookUp[offset][0];
        returnChar = basicGreekLookUp[offset][0];
        if (returnChar == NOCHAR)
        {
            *l = letterToAnalyze;
            return NOCHAR;
        }
        else if (returnChar == NOT_ACCENTABLE_CHAR)
        {
            *l = letterToAnalyze;
            return NOT_ACCENTABLE_CHAR;
        }
        else if (returnChar > NOT_ACCENTABLE_CHAR)
        {
            *l = returnChar;
            *diacritics |= basicGreekLookUp[offset][1];
            //fprintf(stderr, "basic letter: %d, accent: %d", *l, *a);
            return ACCENTABLE_CHAR;
        }
    }
    else if (letterToAnalyze >= 0x1F00 && letterToAnalyze <= 0x1FFF)
    {
        offset = letterToAnalyze - 0x1F00;
        returnChar = extendedGreekLookUp[offset][0];
        if (returnChar == NOCHAR)
        {
            *l = letterToAnalyze;
            return NOCHAR;
        }
        else if (returnChar == NOT_ACCENTABLE_CHAR)
        {
            *l = letterToAnalyze;
            return NOT_ACCENTABLE_CHAR;
        }
        else if (returnChar > NOT_ACCENTABLE_CHAR)
        {
            *l = returnChar;
            *diacritics |= extendedGreekLookUp[offset][1];
            //fprintf(stderr, "extended letter: %d, accent: %d", *l, *a);
            return ACCENTABLE_CHAR;
        }
    }
    else if (letterToAnalyze >= 0xEAF0 && letterToAnalyze <= 0xEB8A)
    {
        offset = letterToAnalyze - 0xEAF0;
        returnChar = puaGreekLookUp[offset][0];
        if (returnChar == NOCHAR)
        {
            *l = letterToAnalyze;
            return NOCHAR;
        }
        else if (returnChar == NOT_ACCENTABLE_CHAR)
        {
            *l = letterToAnalyze;
            return NOT_ACCENTABLE_CHAR;
        }
        else if (returnChar > NOT_ACCENTABLE_CHAR)
        {
            *l = returnChar;
            *diacritics |= puaGreekLookUp[offset][1];
            //fprintf(stderr, "pua letter: %d, accent: %d", *l, *a);
            return ACCENTABLE_CHAR;
        }
    }
    *l = letterToAnalyze;
    return NOCHAR;
}

//return 0 for invalid letter
UCS2 getPrecomposedLetter(int letterIndex, int diacriticMask)
{
    int accentIndex = 0;
    
    switch (diacriticMask)
    {
        case 0:
            accentIndex = NORMAL;
            break;
        case (_SMOOTH):
            accentIndex = PSILI;
            break;
        case (_ROUGH):
            accentIndex = DASIA;
            break;
        case (_ACUTE):
#ifdef USE_TONOS //this is defined, or not, in GreekUnicode.h
            accentIndex = TONOS;
#else
            accentIndex = OXIA;
#endif
            break;
        case (_SMOOTH | _ACUTE):
            accentIndex = PSILI_AND_OXIA;
            break;
        case (_ROUGH | _ACUTE):
            accentIndex = DASIA_AND_OXIA;
            break;
        case  (_GRAVE):
            accentIndex = VARIA;
            break;
        case (_SMOOTH | _GRAVE):
            accentIndex = PSILI_AND_VARIA;
            break;
        case (_ROUGH | _GRAVE):
            accentIndex = DASIA_AND_VARIA;
            break;
        case (_CIRCUMFLEX):
            accentIndex = PERISPOMENI;
            break;
        case (_SMOOTH | _CIRCUMFLEX):
            accentIndex = PSILI_AND_PERISPOMENI;
            break;
        case (_ROUGH | _CIRCUMFLEX):
            accentIndex = DASIA_AND_PERISPOMENI;
            break;
        case (_IOTA_SUB):
            accentIndex = YPOGEGRAMMENI;
            break;
        case (_SMOOTH | _IOTA_SUB):
            accentIndex = PSILI_AND_YPOGEGRAMMENI;
            break;
        case (_ROUGH | _IOTA_SUB):
            accentIndex = DASIA_AND_YPOGEGRAMMENI;
            break;
        case (_ACUTE | _IOTA_SUB):
            accentIndex = OXIA_AND_YPOGEGRAMMENI;
            break;
        case (_SMOOTH | _ACUTE | _IOTA_SUB):
            accentIndex = PSILI_AND_OXIA_AND_YPOGEGRAMMENI;
            break;
        case (_ROUGH | _ACUTE | _IOTA_SUB):
            accentIndex = DASIA_AND_OXIA_AND_YPOGEGRAMMENI;
            break;
        case (_GRAVE | _IOTA_SUB):
            accentIndex = VARIA_AND_YPOGEGRAMMENI;
            break;
        case (_SMOOTH | _GRAVE | _IOTA_SUB):
            accentIndex = PSILI_AND_VARIA_AND_YPOGEGRAMMENI;
            break;
        case (_ROUGH | _GRAVE | _IOTA_SUB):
            accentIndex = DASIA_AND_VARIA_AND_YPOGEGRAMMENI;
            break;
        case (_CIRCUMFLEX | _IOTA_SUB):
            accentIndex = PERISPOMENI_AND_YPOGEGRAMMENI;
            break;
        case (_SMOOTH | _CIRCUMFLEX | _IOTA_SUB):
            accentIndex = PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI;
            break;
        case (_ROUGH | _CIRCUMFLEX | _IOTA_SUB):
            accentIndex = DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI;
            break;
        case (_DIAERESIS):
            accentIndex = DIALYTIKA;
            break;
        case (_ACUTE | _DIAERESIS):
#ifdef USE_TONOS //this is defined, or not, in GreekUnicode.h
            accentIndex = DIALYTIKA_AND_TONOS;
#else
            accentIndex = DIALYTIKA_AND_OXIA;
#endif
            break;
        case (_GRAVE | _DIAERESIS):
            accentIndex = DIALYTIKA_AND_VARIA;
            break;
        case (_CIRCUMFLEX | _DIAERESIS):
            accentIndex = DIALYTIKA_AND_PERISPOMENON;
            break;
        case (_MACRON):
            accentIndex = MACRON_PRECOMPOSED;
            break;
        case (_BREVE):
            accentIndex = BREVE_PRECOMPOSED;
            break;
#ifdef ALLOW_PRIVATE_USE_AREA
        case (_MACRON | _SMOOTH):
            accentIndex = MACRON_AND_SMOOTH;
            break;
        case (_MACRON | _SMOOTH | _ACUTE):
            accentIndex = MACRON_AND_SMOOTH_AND_ACUTE;
            break;
        case (_MACRON | _SMOOTH | _GRAVE):
            accentIndex = MACRON_AND_SMOOTH_AND_GRAVE;
            break;
        case (_MACRON | _ROUGH):
            accentIndex = MACRON_AND_ROUGH;
            break;
        case (_MACRON | _ROUGH | _ACUTE):
            accentIndex = MACRON_AND_ROUGH_AND_ACUTE;
            break;
        case (_MACRON | _ROUGH | _GRAVE):
            accentIndex = MACRON_AND_ROUGH_AND_GRAVE;
            break;
        case (_MACRON | _ACUTE):
            accentIndex = MACRON_AND_ACUTE;
            break;
        case (_MACRON | _GRAVE):
            accentIndex = MACRON_AND_GRAVE;
            break;
        case (_BREVE | _SMOOTH):
            accentIndex = BREVE_AND_SMOOTH;
            break;
        case (_BREVE | _SMOOTH | _ACUTE):
            accentIndex = BREVE_AND_SMOOTH_AND_ACUTE;
            break;
        case (_BREVE | _SMOOTH | _GRAVE):
            accentIndex = BREVE_AND_SMOOTH_AND_GRAVE;
            break;
        case (_BREVE | _ROUGH):
            accentIndex = BREVE_AND_ROUGH;
            break;
        case (_BREVE | _ROUGH | _ACUTE):
            accentIndex = BREVE_AND_ROUGH_AND_ACUTE;
            break;
        case (_BREVE | _ROUGH | _GRAVE):
            accentIndex = BREVE_AND_ROUGH_AND_GRAVE;
            break;
        case (_BREVE | _ACUTE):
            accentIndex = BREVE_AND_ACUTE;
            break;
        case (_BREVE | _GRAVE):
            accentIndex = BREVE_AND_GRAVE;
            break;
#endif
        default:
            return 0; //or set accent = 0 if none of these?
            break;
    }
    if (letterIndex > -1)
        return letters[letterIndex][accentIndex];
    else
        return 0;
}

bool isCombiningDiacritic(UCS2 l)
{
    switch (l)
    {
        case COMBINING_MACRON:
        case COMBINING_ACUTE:
        case COMBINING_GRAVE:
        case COMBINING_CIRCUMFLEX:
        case COMBINING_IOTA_SUBSCRIPT:
        case COMBINING_SMOOTH_BREATHING:
        case COMBINING_ROUGH_BREATHING:
        case COMBINING_DIAERESIS:
        case COMBINING_BREVE:
            return true;
    }
    
    return false;
}

bool isBareVowel(UCS2 l)
{
    switch (l)
    {
        case GREEK_SMALL_LETTER_ALPHA:
        case GREEK_SMALL_LETTER_EPSILON:
        case GREEK_SMALL_LETTER_ETA:
        case GREEK_SMALL_LETTER_IOTA:
        case GREEK_SMALL_LETTER_UPSILON:
        case GREEK_SMALL_LETTER_OMEGA:
        case GREEK_CAPITAL_LETTER_ALPHA:
        case GREEK_CAPITAL_LETTER_EPSILON:
        case GREEK_CAPITAL_LETTER_ETA:
        case GREEK_CAPITAL_LETTER_IOTA:
        case GREEK_CAPITAL_LETTER_UPSILON:
        case GREEK_CAPITAL_LETTER_OMEGA:
            return true;
    }
    
    return false;
}

int ucs2ToLetterIndex(UCS2 l)
{
    if (l == GREEK_SMALL_LETTER_ALPHA)
        return ALPHA;
    else if (l == GREEK_SMALL_LETTER_EPSILON)
        return EPSILON;
    else if (l == GREEK_SMALL_LETTER_ETA)
        return ETA;
    else if (l == GREEK_SMALL_LETTER_IOTA)
        return IOTA;
    else if (l == GREEK_SMALL_LETTER_OMICRON)
        return OMICRON;
    else if (l == GREEK_SMALL_LETTER_UPSILON)
        return UPSILON;
    else if (l == GREEK_SMALL_LETTER_OMEGA)
        return OMEGA;
    else if (l == GREEK_CAPITAL_LETTER_ALPHA)
        return ALPHA_CAP;
    else if (l == GREEK_CAPITAL_LETTER_EPSILON)
        return EPSILON_CAP;
    else if (l == GREEK_CAPITAL_LETTER_ETA)
        return ETA_CAP;
    else if (l == GREEK_CAPITAL_LETTER_IOTA)
        return IOTA_CAP;
    else if (l == GREEK_CAPITAL_LETTER_OMICRON)
        return OMICRON_CAP;
    else if (l == GREEK_CAPITAL_LETTER_UPSILON)
        return UPSILON_CAP;
    else if (l == GREEK_CAPITAL_LETTER_OMEGA)
        return OMEGA_CAP;
    else
        return -1;
}
/*
int letterIndexToUCS2(UCS2 l)
{
    if (l == ALPHA)
        return GREEK_SMALL_LETTER_ALPHA;
    else if (l == EPSILON)
        return GREEK_SMALL_LETTER_EPSILON;
    else if (l == ETA)
        return GREEK_SMALL_LETTER_ETA;
    else if (l == IOTA)
        return GREEK_SMALL_LETTER_IOTA;
    else if (l == OMICRON)
        return GREEK_SMALL_LETTER_OMICRON;
    else if (l == UPSILON)
        return GREEK_SMALL_LETTER_UPSILON;
    else if (l == OMEGA)
        return GREEK_SMALL_LETTER_OMEGA;
    else if (l == ALPHA_CAP)
        return GREEK_CAPITAL_LETTER_ALPHA;
    else if (l == EPSILON_CAP)
        return GREEK_CAPITAL_LETTER_EPSILON;
    else if (l == ETA_CAP)
        return GREEK_CAPITAL_LETTER_ETA;
    else if (l == IOTA_CAP)
        return GREEK_CAPITAL_LETTER_IOTA;
    else if (l == OMICRON_CAP)
        return GREEK_CAPITAL_LETTER_OMICRON;
    else if (l == UPSILON_CAP)
        return GREEK_CAPITAL_LETTER_UPSILON;
    else if (l == OMEGA_CAP)
        return GREEK_CAPITAL_LETTER_OMEGA;
    else
        return 0;
}
*/
bool isLegalDiacriticForLetter(UCS2 letter, int accentToAdd)
{
    switch (accentToAdd)
    {
        case CIRCUMFLEX:
            if (letter != GREEK_SMALL_LETTER_ALPHA && 
                letter != GREEK_SMALL_LETTER_ETA && 
                letter != GREEK_SMALL_LETTER_IOTA && 
                letter != GREEK_SMALL_LETTER_UPSILON && 
                letter != GREEK_SMALL_LETTER_OMEGA && 
                letter != GREEK_CAPITAL_LETTER_ALPHA && 
                letter != GREEK_CAPITAL_LETTER_ETA && 
                letter != GREEK_CAPITAL_LETTER_IOTA && 
                letter != GREEK_CAPITAL_LETTER_UPSILON && 
                letter != GREEK_CAPITAL_LETTER_OMEGA) {
                return false;
            }
            break;
        case MACRON:
            if (letter != GREEK_SMALL_LETTER_ALPHA && 
                letter != GREEK_SMALL_LETTER_IOTA && 
                letter != GREEK_SMALL_LETTER_UPSILON && 
                letter != GREEK_CAPITAL_LETTER_ALPHA && 
                letter != GREEK_CAPITAL_LETTER_IOTA && 
                letter != GREEK_CAPITAL_LETTER_UPSILON) {
                return false;
            }
            break;
        case BREVE:
            if (letter != GREEK_SMALL_LETTER_ALPHA && 
                letter != GREEK_SMALL_LETTER_IOTA && 
                letter != GREEK_SMALL_LETTER_UPSILON && 
                letter != GREEK_CAPITAL_LETTER_ALPHA && 
                letter != GREEK_CAPITAL_LETTER_IOTA && 
                letter != GREEK_CAPITAL_LETTER_UPSILON) {
                return false;
            }
            break;
        case IOTA_SUBSCRIPT:
            if (letter != GREEK_SMALL_LETTER_ALPHA && 
                letter != GREEK_SMALL_LETTER_ETA && 
                letter != GREEK_SMALL_LETTER_OMEGA && 
                letter != GREEK_CAPITAL_LETTER_ALPHA && 
                letter != GREEK_CAPITAL_LETTER_ETA && 
                letter != GREEK_CAPITAL_LETTER_OMEGA) {
                return false;
            }
            break;
        case DIAERESIS:
            if (letter != GREEK_SMALL_LETTER_IOTA && 
                letter != GREEK_SMALL_LETTER_UPSILON && 
                letter != GREEK_CAPITAL_LETTER_IOTA && 
                letter != GREEK_CAPITAL_LETTER_UPSILON) {
                return false;
            }
            break;
    }
    return true;
}

//adjusts diacritics based on one being added
unsigned int updateDiacritics(UCS2 letter, int accentToAdd, unsigned int diacritics, bool toggleOff)
{
    switch (accentToAdd)
    {
        case ACUTE:
            if (toggleOff && (diacritics & _ACUTE) == _ACUTE)
                diacritics &= ~_ACUTE;
            else
                diacritics |= _ACUTE;
            diacritics &= ~(_GRAVE | _CIRCUMFLEX); //turn off...
            break;
        case CIRCUMFLEX:
            if (toggleOff && (diacritics & _CIRCUMFLEX) == _CIRCUMFLEX)
                diacritics &= ~_CIRCUMFLEX;
            else
                diacritics |= _CIRCUMFLEX;
            diacritics &= ~(_ACUTE | _GRAVE | _MACRON);
            break;
        case GRAVE:
            if (toggleOff && (diacritics & _GRAVE) == _GRAVE)
                diacritics &= ~_GRAVE;
            else
                diacritics |= _GRAVE;
            diacritics &= ~(_ACUTE | _CIRCUMFLEX);
            break;
        case MACRON:
            if (toggleOff && (diacritics & _MACRON) == _MACRON)
                diacritics &= ~_MACRON;
            else
                diacritics |= _MACRON;
            diacritics &= ~_CIRCUMFLEX;
            diacritics &= ~_BREVE;
            break;
        case BREVE:
            if (toggleOff && (diacritics & _BREVE) == _BREVE)
                diacritics &= ~_BREVE;
            else
                diacritics |= _BREVE;
            diacritics &= ~_CIRCUMFLEX;
            diacritics &= ~_MACRON;
            diacritics &= ~_IOTA_SUB;
            break;
        case ROUGH_BREATHING:
            if (toggleOff && (diacritics & _ROUGH) == _ROUGH)
                diacritics &= ~_ROUGH;
            else
                diacritics |= _ROUGH;
            diacritics &= ~(_SMOOTH | _DIAERESIS);
            break;
        case SMOOTH_BREATHING:
            if (toggleOff && (diacritics & _SMOOTH) == _SMOOTH)
                diacritics &= ~_SMOOTH;
            else
                diacritics |= _SMOOTH;
            diacritics &= ~(_ROUGH | _DIAERESIS);
            break;
        case IOTA_SUBSCRIPT:
            if (toggleOff && (diacritics & _IOTA_SUB) == _IOTA_SUB)
                diacritics &= ~_IOTA_SUB;
            else
                diacritics |= _IOTA_SUB;
            diacritics &= ~_BREVE;
            break;
        case UNDERDOT:
            if (toggleOff && (diacritics & _UNDERDOT) == _UNDERDOT)
                diacritics &= ~_UNDERDOT;
            else
                diacritics |= _UNDERDOT;
            break;
        case DIAERESIS:
            if (letter == GREEK_CAPITAL_LETTER_IOTA || letter == GREEK_CAPITAL_LETTER_UPSILON) {
                diacritics &= ~(_ACUTE | _GRAVE | _CIRCUMFLEX | _MACRON);
            }
            
            if (toggleOff && (diacritics & _DIAERESIS) == _DIAERESIS)
                diacritics &= ~_DIAERESIS;
            else
                diacritics |= _DIAERESIS;
            diacritics &= ~(_SMOOTH | _ROUGH);
            break;
        default:
            break;
    }
    return diacritics;
}

/*
 Returns the length of letter(1) + any combining diacritics up to MAX_COMBINING
 Passes bitfield back of diacritics found
 */
int analyzeCombiningChars(UCS2 *cp, int len, unsigned int *diacritics)
{
    int letterLen = 1; //assume first character is a non-combining letter
    for ( ; letterLen <= MAX_COMBINING && letterLen < len; letterLen++)
    {
        if (cp[letterLen] == COMBINING_ROUGH_BREATHING) {
            *diacritics |= _ROUGH;
        }
        else if (cp[letterLen] == COMBINING_SMOOTH_BREATHING) {
            *diacritics |= _SMOOTH;
        }
        else if (cp[letterLen] == COMBINING_ACUTE) {
            *diacritics |= _ACUTE;
        }
        else if (cp[letterLen] == COMBINING_GRAVE) {
            *diacritics |= _GRAVE;
        }
        else if (cp[letterLen] == COMBINING_CIRCUMFLEX) {
            *diacritics |= _CIRCUMFLEX;
        }
        else if (cp[letterLen] == COMBINING_MACRON) {
            *diacritics |= _MACRON;
        }
        else if (cp[letterLen] == COMBINING_BREVE) {
            *diacritics |= _BREVE;
        }
        else if (cp[letterLen] == COMBINING_IOTA_SUBSCRIPT) {
            *diacritics |= _IOTA_SUB;
        }
        else if (cp[letterLen] == COMBINING_DIAERESIS) {
            *diacritics |= _DIAERESIS;
        }
        else if (cp[letterLen] == COMBINING_UNDERDOT) {
            *diacritics |= _UNDERDOT;
        }
        else {
            break;
        }
    }

    return letterLen;
}

//passes back the letterCode and diacriticMask for this letter
//returns the number of characters or -1, if not valid or unknown
size_t analyzeLetter(UCS2 *ucs2String, int len, UCS2 *letter, unsigned int *diacritics, UCS2 *type)
{
    *diacritics = 0; //start at nothing
    *letter = 0;
    //always returns at least one for the first char.
    //these diacritics are then passed into and added to in analyzePrecomposedLetter
    int letterLen = analyzeCombiningChars(ucs2String, len, diacritics);
    
    *type = analyzePrecomposedLetter(*ucs2String, letter, diacritics);
    
    return letterLen;
}

/*
ucs2String must have at least NUM_COMBINING_ACCENTS + 1 slots to grow
*/
void makeLetterCombining(UCS2 *ucs2String, int *letterLen, UCS2 letter, unsigned int diacritics)
{
    *letterLen = 0;
    ucs2String[(*letterLen)++] = letter; //set base letter

    //loop so that order is determined by combiningAccents array
    for (int k = 0; k < NUM_COMBINING_ACCENTS; k++)
    {
        if (combiningAccents[k] == COMBINING_MACRON && (diacritics & _MACRON) == _MACRON) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_BREVE && (diacritics & _BREVE) == _BREVE) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_ROUGH_BREATHING && (diacritics & _ROUGH) == _ROUGH) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_SMOOTH_BREATHING && (diacritics & _SMOOTH) == _SMOOTH) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_ACUTE && (diacritics & _ACUTE) == _ACUTE) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_GRAVE && (diacritics & _GRAVE) == _GRAVE) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_CIRCUMFLEX && (diacritics & _CIRCUMFLEX) == _CIRCUMFLEX) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_IOTA_SUBSCRIPT && (diacritics & _IOTA_SUB) == _IOTA_SUB) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_DIAERESIS && (diacritics & _DIAERESIS) == _DIAERESIS) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
        else if (combiningAccents[k] == COMBINING_UNDERDOT && (diacritics & _UNDERDOT) == _UNDERDOT) {
            ucs2String[(*letterLen)++] = combiningAccents[k];
        }
    }

    /* The loop above results in smaller code in EMPSCRIPTEN???
    //in order that they should appear
    if ( (diacritics & _MACRON) == _MACRON ){
        ucs2String[(*letterLen)++] = COMBINING_MACRON;
    }
    if ( (diacritics & _BREVE) == _BREVE ) {
        ucs2String[(*letterLen)++] = COMBINING_BREVE;
    }
    if ( (diacritics & _ROUGH) == _ROUGH ) {
        ucs2String[(*letterLen)++] = COMBINING_ROUGH_BREATHING;
    }
    if ( (diacritics & _SMOOTH) == _SMOOTH ) {
        ucs2String[(*letterLen)++] = COMBINING_SMOOTH_BREATHING;
    }
    if ( (diacritics & _ACUTE) == _ACUTE ) {
        ucs2String[(*letterLen)++] = COMBINING_ACUTE;
    }
    if ( (diacritics & _GRAVE) == _GRAVE ) {
        ucs2String[(*letterLen)++] = COMBINING_GRAVE;
    }
    if ( (diacritics & _CIRCUMFLEX) == _CIRCUMFLEX ) {
        ucs2String[(*letterLen)++] = COMBINING_CIRCUMFLEX;
    }
    if ( (diacritics & _IOTA_SUB) == _IOTA_SUB ) {
        ucs2String[(*letterLen)++] = COMBINING_IOTA_SUBSCRIPT;
    }
    if ( (diacritics & _DIAERESIS) == _DIAERESIS ) {
        ucs2String[(*letterLen)++] = COMBINING_DIAERESIS;
    }
    if ( (diacritics & _UNDERDOT) == _UNDERDOT) {
        ucs2String[(*letterLen)++] = COMBINING_UNDERDOT;
    }*/
}

bool makeLetter(UCS2 *ucs2String, int *newLetterLen, UCS2 letter, unsigned int diacritics, int unicodeMode)
{
    //Use PUA, - almost all precomposing except alpha macron, breathing, accent, iota_sub, if iota_sub use combining
    //Use both, if macron use combining
    //Use only combining accents
    int i = 0;
    //fallback if macron + one more diacritic
    bool precomposingFallbackToComposing = false;
    if ((unicodeMode == PRECOMPOSED_MODE && (diacritics & _MACRON) == _MACRON) || (unicodeMode == PRECOMPOSED_WITH_PUA_MODE && (diacritics & (_MACRON | _DIAERESIS)) == (_MACRON | _DIAERESIS)))
    {
        if ((diacritics & ~_MACRON) != 0)//if any other bits set besides macron
        {
            precomposingFallbackToComposing = true;
        }
    }
    else if ((unicodeMode == PRECOMPOSED_MODE && (diacritics & _BREVE) == _BREVE))
    {
        if ((diacritics & ~_BREVE) != 0)//if any other bits set besides macron
        {
            precomposingFallbackToComposing = true;
        }
    }
    else if (unicodeMode == PRECOMPOSED_HC_MODE && (diacritics & _MACRON) == _MACRON)
    {
        //this is legacy for the hoplite challenge app which uses combining macron even if no other diacritics
        precomposingFallbackToComposing = true;
    }

    *newLetterLen = 1;
    if (unicodeMode == COMBINING_ONLY_MODE || precomposingFallbackToComposing)
    {
        makeLetterCombining(ucs2String, newLetterLen, letter, diacritics);
        return true;
    }
    else
    {
        //fix me
        bool needToAddIotaSubscript = false;
        if (unicodeMode == PRECOMPOSED_WITH_PUA_MODE && (diacritics & (_IOTA_SUB | _MACRON)) == (_IOTA_SUB | _MACRON))
        {
            needToAddIotaSubscript = true;
            diacritics &= ~_IOTA_SUB; //so we don't get two iota subscripts
        }

        int letterIndex = ucs2ToLetterIndex(letter);

        if (letterIndex < 0)
        {
            //still add underdot even if not a vowel
            if ((diacritics & _UNDERDOT) == _UNDERDOT)
            {
                ucs2String[i+1] = COMBINING_UNDERDOT;
                (*newLetterLen)++;
                return true;
            }
            else
            {
                return false;
            }
        }

        bool needToAddUnderdot = false;
        if ((diacritics & _UNDERDOT) == _UNDERDOT)
        {
            needToAddUnderdot = true;
            diacritics &= ~_UNDERDOT; //turn off while we add precomposed char
        }

        UCS2 ucs2 = getPrecomposedLetter(letterIndex, diacritics);
        if (ucs2 != 0)
        {
            ucs2String[i] = ucs2;
            if (needToAddIotaSubscript)
            {
                (*newLetterLen)++;
                ucs2String[++i] = COMBINING_IOTA_SUBSCRIPT;
            }
            if (needToAddUnderdot)
            {
                ucs2String[++i] = COMBINING_UNDERDOT;
                (*newLetterLen)++;
            }
            return true;
        }
        else
        {
            return false;
        }
    }
}

UCS2 getSpacingDiacritic(int diacritic)
{
    switch (diacritic)
    {
        case ACUTE:
            return 0x00B4;
            break;
        case GRAVE:
            return 0x0060;
            break;
        case CIRCUMFLEX:
            return 0x005E;
            break;
        case MACRON:
            return 0x00AF;
            break;
        case BREVE:
            return 0x02D8;
            break;
        case DIAERESIS:
            return 0x00A8;
            break;
        case ROUGH_BREATHING:
            return 0x02BD;
            break;
        case SMOOTH_BREATHING:
            return 0x02BC;
            break;
        case IOTA_SUBSCRIPT:
            return 0x037A;
            break;
        default:
            return 0;
    }
}

//wasm / emscripten / webassembly
//emcc -std=gnu99 -Oz -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_accentSyllable2','_stripDiacritics']" -Wl,--no-entry "utilities.c" "accent.c" -o "hoplitekb.wasm"
int accentSyllable2(UCS2 *ucs2String, int len, int accentToAdd, int toggleOff, int unicodeMode)
{
    accentSyllable(ucs2String, &len, accentToAdd, toggleOff, unicodeMode);
    return len;
}

int compareUTF8(char *s1, char *s2, int compareType)
{
    UCS2 a1[strlen(s1)*2];
    UCS2 a2[strlen(s2)*2];
    size_t len1, len2;

    utf8_to_ucs2_string(s1, a1, &len1);
    utf8_to_ucs2_string(s2, a2, &len2);

    return compare(a1, len1, a2, len2, compareType);
}
//binary
//diacritic sensitve, but accepts composed/decomposed equally
//accent insensitive, but breathing/iota subscript/macron/breve/diaeresis sensitive
//diacritic insensitive
//unknown chars sensitive/insensitive

//ignore unknown
//compare unknown chars as binary: useful for spaces, punc, etc.
//unknown always sort above/below known
//consider unknown the end of word

//compareType includes which diacritics to be insensitive to and also whether to ignore non-greek and, in the future to test case
int compare(UCS2 *s1, size_t len1, UCS2 *s2, size_t len2, int compareType)
{
    size_t i1 = 0;
    size_t i2 = 0;
    UCS2 temp1 = 0;
    UCS2 temp2 = 0;
    unsigned int diacritics1 = 0;
    unsigned int diacritics2 = 0;
    UCS2 type1 = 0;
    UCS2 type2 = 0;

    while (i1 < len1 && i2 < len2)
    {
        size_t l1 = analyzeLetter(&s1[i1], len1 - i1, &temp1, &diacritics1, &type1);
        size_t l2 = analyzeLetter(&s2[i2], len2 - i2, &temp2, &diacritics2, &type2);

        if ((compareType & _HK_IGNORE_UNKNOWN_CHARS) == _HK_IGNORE_UNKNOWN_CHARS && type1 == NOCHAR)
        {
            i1 += l1;
            continue;
        }
        else if ((compareType & _HK_IGNORE_UNKNOWN_CHARS) == _HK_IGNORE_UNKNOWN_CHARS && type2 == NOCHAR)
        {
            i2 += l2;
            continue;
        }
        else
        {
            i1 += l1;
            i2 += l2;
        }
        if (temp1 < 0x0370 || temp1 > 0x03FF || temp2 < 0x0370 || temp2 > 0x03FF) //non-greek = not equal
        {
            return 1; //we do not care about sort order for this, for now: just return 1.
        }

        if (basicGreekLookUp[temp1 - 0x0370][2] < basicGreekLookUp[temp2 - 0x0370][2])
        {
            return -1;
        }
        else if (basicGreekLookUp[temp1 - 0x0370][2] > basicGreekLookUp[temp2 - 0x0370][2])
        {
            return 1;
        }

        if ( (diacritics1 & ~compareType) != (diacritics2 & ~compareType) )
        {
            return 1; //we do not care about sort order for this, for now: just return 1.
        }
    }

    if (i1 == len1 && i2 == len2) //both at end
    {
        return 0;
    }
    else if (i1 == len1) //1 at end
    {
        return -1;
    }
    else //2 at end
    {
        return 1;
    }
}

int stripDiacritics(UCS2 *ucs2String, int len, int removeNonGreek)
{
    UCS2 tempChar, type;
    UCS2 *p = ucs2String;
    unsigned int diacritics;
    int strEnd = 0;
    UCS2 *end = p + len;
    int i = 0;
    while ( p < end )
    {
        size_t letterLen = analyzeLetter(p, len - i, &tempChar, &diacritics, &type);
        p += letterLen;
        i += letterLen;
        if (type != NOCHAR || !removeNonGreek)
        {
            ucs2String[strEnd++] = tempChar;
        }
    }
    len = strEnd;
    return len;
}

/*
int convert(char *utf8, UCS2 *ucs2String, int len, int unicodemode)
{
    //convert to ucs2 minding len buffer length
    //then walk the ucs2 string converting it in place
}
*/
void convertString(UCS2 *str, int len, UCS2 *buffer, int *bufferLen, int bufferCapacity, int unicodeMode)
{
    UCS2 baseLetter = 0;
    unsigned int diacritics = 0;
    UCS2 type = 0;

    *bufferLen = 0;
    UCS2 *b2 = buffer;
    size_t i = 0;
    int tempBLen = 0;

    for ( ; i < len && *bufferLen + MAX_COMBINING < bufferCapacity; ) {
        size_t letterLen = analyzeLetter(&str[i], len - i, &baseLetter, &diacritics, &type);
        //printf("len %d\n", letterLen);
        if (!makeLetter(b2, &tempBLen, baseLetter, diacritics, unicodeMode)) {
            assert(1 == 2);
            return;
        }

        i += letterLen;
        b2 += tempBLen;
        *bufferLen += tempBLen;
    }
}

/*
void accentContext(UCS2 *str, int *len, int cursorPos)
{
    for (int i = cursorPos; i < *len; i++)
    {
        if ( !isCombining(str[i]) ) {
            break;
        }
    }
}

*/

//there should be room for a least MAX_COMBINING more characters at the end of ucs2String, in case it needs to grow
void accentSyllable(UCS2 *ucs2String, int *len, int accentToAdd, bool toggleOff, int unicodeMode)
{
    /* remove?
    if (accentToAdd == UNDERDOT)
    {
        if (ucs2String[*len - 1] == COMBINING_UNDERDOT)
        {
            //ucs2String[i + *len - 1] = 0x0000;
            //--(*len);
            ucsplice(ucs2String, len, 1024, i + *len - 1, 1, NULL, 0);

        } else {
            //ucs2String[i + *len] = COMBINING_UNDERDOT;
            //++(*len);
            ucsplice(ucs2String, len, 1024, i + *len, 0, (UCS2[]){COMBINING_UNDERDOT}, 1);
        }
        return;
    }
*/
    if (unicodeMode != PRECOMPOSED_MODE && unicodeMode != PRECOMPOSED_WITH_PUA_MODE && unicodeMode != COMBINING_ONLY_MODE && unicodeMode != PRECOMPOSED_HC_MODE)
    {
        unicodeMode = PRECOMPOSED_MODE;
    }
    unicode_mode = unicodeMode;
    if (*len < 1) {
        if (addSpacingDiacriticIfNotLegal) {
            UCS2 sd = getSpacingDiacritic(accentToAdd);
            if (sd) {
                *ucs2String = sd;
                *len = 1;
            }
        }
        return;
    }

    //1. handle consonants
    if (*ucs2String == GREEK_SMALL_LETTER_RHO && accentToAdd == ROUGH_BREATHING)
    {
        *ucs2String = GREEK_SMALL_LETTER_RHO_WITH_DASIA;
        return;
    }
    else if (*ucs2String == GREEK_SMALL_LETTER_RHO_WITH_DASIA && accentToAdd == ROUGH_BREATHING)
    {
        *ucs2String = GREEK_SMALL_LETTER_RHO;
        return;
    }
    else if (*ucs2String == GREEK_CAPITAL_LETTER_RHO && accentToAdd == ROUGH_BREATHING)
    {
        *ucs2String = GREEK_CAPITAL_LETTER_RHO_WITH_DASIA;
        return;
    }
    else if (*ucs2String == GREEK_CAPITAL_LETTER_RHO_WITH_DASIA && accentToAdd == ROUGH_BREATHING)
    {
        *ucs2String = GREEK_CAPITAL_LETTER_RHO;
        return;
    }
    else if (*ucs2String == GREEK_SMALL_LETTER_RHO_WITH_PSILI && accentToAdd == ROUGH_BREATHING)
    {
        *ucs2String = GREEK_SMALL_LETTER_RHO_WITH_DASIA;
        return;
    }
#ifdef ALLOW_RHO_WITH_PSILI
    else if (*ucs2String == GREEK_SMALL_LETTER_RHO && accentToAdd == SMOOTH_BREATHING)
    {
        *ucs2String = GREEK_SMALL_LETTER_RHO_WITH_PSILI;
        return;
    }
    else if (*ucs2String == GREEK_SMALL_LETTER_RHO_WITH_PSILI && accentToAdd == SMOOTH_BREATHING)
    {
        *ucs2String = GREEK_SMALL_LETTER_RHO;
        return;
    }
    else if (*ucs2String == GREEK_SMALL_LETTER_RHO_WITH_DASIA && accentToAdd == SMOOTH_BREATHING)
    {
        *ucs2String = GREEK_SMALL_LETTER_RHO_WITH_PSILI;
        return;
    }
#endif
    else if (*ucs2String == GREEK_SMALL_LETTER_NU && accentToAdd == SURROUNDING_PARENTHESES)
    {
        /*rightShiftFromOffsetSteps(ucs2String, i, 2, len);
         ucs2String[i] = LEFT_PARENTHESIS;
         ucs2String[i+1] = GREEK_SMALL_LETTER_NU;
         ucs2String[i+2] = RIGHT_PARENTHESIS; */
        ucsplice(ucs2String, len, 1024, 0, 1, (UCS2[]){LEFT_PARENTHESIS,GREEK_SMALL_LETTER_NU,RIGHT_PARENTHESIS }, 3);
        return;
    }

    //2. now analyze what is currently there
    UCS2 baseLetter = 0;
    unsigned int diacritics = 0;
    
    //this will be -1 on error
    UCS2 type = 0;
    size_t letterLen = analyzeLetter(ucs2String, *len, &baseLetter, &diacritics, &type);
    if (type != ACCENTABLE_CHAR) {

        if (accentToAdd == UNDERDOT)
        {
            if ((diacritics & _UNDERDOT) == _UNDERDOT)
            {
                (*len)--;
            } else {
                ucsplice(ucs2String, len, 1024, *len, 0, (UCS2[]){COMBINING_UNDERDOT}, 1);
            }
        }
        else if (addSpacingDiacriticIfNotLegal) {
            UCS2 sd = getSpacingDiacritic(accentToAdd);
            if (sd) {
                ucs2String[1] = sd;
                *len += 1;
            }
        }
        return;
    }

    //2.5: return if this diacritic isn't legal for the letter it's being added to
    if (!isLegalDiacriticForLetter(baseLetter, accentToAdd)) {
        if (addSpacingDiacriticIfNotLegal) {
            UCS2 sd = getSpacingDiacritic(accentToAdd);
            if (sd) {
                ucs2String[1] = sd;
                *len += 1;
            }
        }
        return;
    }

    //3. this changes old letter analysis to the one we want
    diacritics = updateDiacritics(baseLetter, accentToAdd, diacritics, toggleOff);

    //4. this creates the new letter, either with combining or precomposed accents
    UCS2 buffer[MAX_COMBINING]; //this is letter plus max combining
    int newLetterLen = 0;

    if (!makeLetter(buffer, &newLetterLen, baseLetter, diacritics, unicodeMode))
        return;
    //5. make room for letter or decrease it if it is shrinking
    ucsplice(ucs2String, len, 1024, 0, letterLen, buffer, newLetterLen);
}

/*
#include <stdlib.h>
char buf[1024];
char *accentSyllableUtf8(char *utf8, int accent)
{
    UCS2 ucs2[20];
    char *new;
    new = malloc(100);
    unsigned long len = 0;//mystrlen(utf8);
    utf8_to_ucs2_string((unsigned char*)utf8, ucs2, (int*)&len);

    accentSyllable(ucs2, 0, (int*)&len, accent, 1, PRECOMPOSED_MODE);

    ucs2_to_utf8_string(ucs2, (int)len, (unsigned char*)new);
    
    //new[0] = 'a';
    //new[1] = 'b';
    //new[2] = '\n';
    
    return new;
}

*/


//helper function to make it easier to import into swift
/*
 void accentSyllable16(uint16_t *ucs2String, int i, int *len, int accent, bool toggleOff, int mode)
 {
 accentSyllable2((UCS2*)ucs2String, i, len, accent, toggleOff, mode);
 }
 */
